name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update browserslist database
      run: npx update-browserslist-db@latest
    
    - name: Type check
      run: npx tsc --noEmit
    
    - name: Lint
      run: npx eslint src --ext .ts,.tsx --max-warnings 0
    
    - name: Build
      run: npm run build
    
    - name: Test build output
      run: |
        if [ ! -f "dist/public/index.html" ]; then
          echo "Build failed: index.html not found"
          exit 1
        fi
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: server index.js not found"
          exit 1
        fi
        echo "Build successful"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 1
